archive/grewtix/grewtix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('tickets.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

archive/grewtix/tickets/urls.py
from django.urls import path, re_path

from . import views

app_name = 'tickets'
urlpatterns = [
    path('', views.index, name='index'),
    path('owned_by_user_queue/', views.OwnedByUserView.as_view(), name='owned_by_user_queue'),
    path('created_by_user_queue/', views.CreatedByUserView.as_view(), name='created_by_user_queue'),
    path('unassigned_queue/', views.UnassignedView.as_view(), name='unassigned_queue'),
    path('recently_created_queue/', views.RecentlyCreatedView.as_view(), name='recently_created_queue'),
    path('all_ticket_queue/', views.AllTicketsView.as_view(), name='all_ticket_queue'),

    path('create/', views.TicketCreate.as_view(), name='create'),
    # re_path(r'^edit/[a-zA-Z]+[-][0-9]+', views.ticketedit, name='edit'),
    path('edit/<int:pk>', views.TicketUpdate.as_view(), name='edit'),
    path('<pk>/delete/', views.TicketDelete.as_view(), name='delete'),
    path('assign/<int:ticket_id>', views.TicketAssign, name="assign"),
    path('reports/', views.reports, name="reports")
    #path('comment/<int:comment>', views.CommentOnTicket, name="comment"),
]

grewtix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tickets/', include("tickets.urls")),
]

tickets/urls.py
from django.urls import path
from . import views

app_name = 'tickets'
urlpatterns = [
    path("", views.ticket_index, name="ticket_index"),
    path('create/', views.TicketCreate.as_view(), name='ticket_create'),
    path('detail/<int:pk>', views.TicketDetail.as_view(), name='ticket_detail'),
    path('edit/<int:pk>', views.TicketUpdate.as_view(), name='ticket_edit'),
    path('delete/<int:pk>', views.TicketDelete.as_view(), name='ticket_delete'),

    path('owner/', views.OwnedByUserView.as_view(), name='ticket_owner_queue'),
    path('created_by/', views.CreatedByUserView.as_view(), name='ticket_created_queue'),
    path('unassigned/', views.UnassignedView.as_view(), name='ticket_unassigned_queue'),
    path('recent/', views.RecentlyCreatedView.as_view(), name='ticket_recent_queue'),
    path('all/', views.AllTicketsView.as_view(), name='ticket_all_queue'),

    path('reports/', views.reports, name="ticket_reports"),
]

ttsystem/ttsystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('tickets.urls')),
    path('admin/', admin.site.urls),
]

archive/grewtix/tickets/models.py
from django.db import models
from django.utils import timezone, dateformat
from django.contrib.auth.models import User


# Create your models here.

class TimeStampMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class TicketType(TimeStampMixin): #1 to many
    ticketType = models.CharField(max_length=5)
    
    def __str__(self):
        return self.ticketType

class Project(TimeStampMixin): #1 to many
    project = models.CharField(max_length=50)

    def __str__(self):
        return self.project

class Priority(TimeStampMixin): #1 to many
    priority = models.CharField(max_length=10)

    def __str__(self):
        return self.priority

class Status(TimeStampMixin): #1 to many
    status = models.CharField(max_length=20)

    def __str__(self):
        return self.status

class Ticket(TimeStampMixin):

    PRIORITY_CHOICES = ( 
        ('Low','Low'),
        ('Medium','Medium'),
        ('High','High'),
        ('Critical','Critical'),
    )

    STATUS_CHOICES = ( 
        ('Backlog','Backlog'),
        ('Waiting On Submitter','Waiting On Submitter'),
        ('In Progress','In Progress'),
        ('Waiting On Support','Waiting On Support'),
    )

    ticketType = models.ForeignKey(TicketType, on_delete=models.CASCADE)
    subject = models.CharField(max_length=75)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    description = models.TextField(max_length=1000, default='')
    priority = models.CharField(max_length=10,choices=PRIORITY_CHOICES, blank=True) #Priority, on_delete=models.CASCADE, blank=True) #needs to be removed and replaced with list
    status = models.CharField(max_length=40,choices=STATUS_CHOICES, blank=True)
    creator = models.ForeignKey(User, related_name='creator', on_delete=models.CASCADE)
    owner = models.ForeignKey(User, related_name='owner', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.ticketType.ticketType + '-' + str(self.id)

    def how_many_days_old(self):
        # date_object = dateformat.format(timezone.now(), 'd' - dateformat.format(self.created_at,'d')
        delta = timezone.now() - self.created_at
        return delta.days

    def get_comments(self):
        queryset = Comment.objects.filter(ticketID=self.id)
        if queryset:
            return queryset
        else:
            return None

class Attachment(TimeStampMixin): #1 to many
    ticketID = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    filepath = models.CharField(max_length=150)

class Comment(TimeStampMixin): #1 to many
    ticketID = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    comment = models.CharField(max_length=500)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return 'Comment {} by {}'.format(self.comment, self.creator)

    def how_many_days_old(self):
        # date_object = dateformat.format(timezone.now(), 'd' - dateformat.format(self.created_at,'d')
        delta = timezone.now() - self.created_at
        return delta.days

archive/grewtix/tickets/forms.py
from django import forms
from .models import Ticket, Comment

class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        
        widgets = {
        #     'subject' : forms.TextInput(attrs={"class": "form-control-plaintext bg-light"})
            'description': forms.Textarea(),
            'creator': forms.HiddenInput(),
        }

        fields = [
            'ticketType',
            'subject',
            'project',
            'description',
            'priority',
            'status',
            'creator',
            'owner',
        ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment

        widgets = {
            'comment': forms.Textarea(),
            'creator': forms.HiddenInput(),
        }

        fields = ['comment', 'creator']

archive/grewtix/tickets/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic 
from django.urls import reverse
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.base import ContextMixin, TemplateResponseMixin
from django.http import HttpResponse, HttpResponseRedirect
from os import path

from .forms import TicketForm, CommentForm
from .models import Ticket, Comment

def TicketAssign(request, ticket_id):
    ticket = Ticket.objects.get(id=ticket_id)
    ticket.owner = User.objects.get(id=request.user.id)
    ticket.save()
    return HttpResponseRedirect(reverse('tickets:edit', kwargs={'pk': ticket.id}))

def CommentOnTicket(request, comment):
    pass

def index(request):
    return render(request, 'tickets/index.html')

# def ticketedit(request):
#     split_path = path.split(request.path)
#     ticket_split_by_dash = split_path[1].split('-')
#     ticket_id = ticket_split_by_dash[1]
#     if Ticket.objects.filter(pk=int(ticket_id)).exists():
#         ticket_object = Ticket.objects.get(pk=int(ticket_id))
#         if split_path[1].lower() == str(ticket_object).lower():
#             return HttpResponseRedirect(reverse('tickets:edit', kwargs={'pk': ticket_id}))
#     else:
#         return HttpResponse("Could not find the ticket you are looking for.") 

def reports(request):
    return render(request, 'tickets/ticket_reports.html')


##############################
# Returns different query sets for the ticket class
class TicketListView(generic.ListView):
    template_name = 'tickets/ticket_display_queryset.html'
    context_object_name = 'ticket_list'

class RecentlyCreatedView(TicketListView):
    def get_queryset(self):
        """Return the last five published Tickets."""
        return Ticket.objects.order_by('-created_at')[:4]

class OwnedByUserView(TicketListView):
    def get_queryset(self):
        return Ticket.objects.filter(owner=self.request.user.id).order_by('-created_at')

class CreatedByUserView(TicketListView):
    def get_queryset(self):
        return Ticket.objects.filter(creator=self.request.user.id).order_by('-created_at')

class UnassignedView(TicketListView):
    def get_queryset(self):
        return Ticket.objects.filter(owner=None).order_by('-created_at')

class AllTicketsView(TicketListView):
    def get_queryset(self):
        return Ticket.objects.all().order_by('-created_at')
##############################

##############################
# Handles all the CRUD operations for ticket
class TicketFormView():
    model = Ticket
    form_class = TicketForm

    def get_success_url(self):
        return reverse('tickets:index')

class TicketCreate(TicketFormView, CreateView):
    template_name = 'tickets/ticket_create_form.html'
    form_class = TicketForm

class TicketUpdate(TicketFormView, UpdateView):
    template_name = 'tickets/ticket_update_form.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # context['ticket_form'] = TicketForm
        context['comment_form'] = CommentForm
        print("********************************************************************************")
        return context

class TicketDelete(TicketFormView, DeleteView):
    pass

# class MultiFormViews(TemplateResponseMixin, BaseMul)

##############################

grewtix/templates/base.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

grewtix/templates/header.html
{% include 'base.html' %}
{% load static %}

<link rel="icon"href="{% static 'img/my-logo.png' %}">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
  integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<link type='text/css' rel="stylesheet" href="{% static 'css/main.css' %}">

<style>
  .grew-logo {
    background-image: url("{% static 'img/my-logo.png' %}");
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top" id='home-nav'>
  <div class="container">
    <a class="navbar-brand" href="{% url 'tickets:ticket_index' %}">
      <div class="grew-logo" aria-hidden="true"></div>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
      aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link grew-link uppercase" href="{% url 'tickets:ticket_reports'%}">Reports</a>
        </li>
        <li class="nav-item">
          <a class="nav-link grew-link uppercase" href="/admin">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tickets:ticket_create'%}"><button class="grew-btn uppercase">Create
              Issue</button></a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <div class="row">
            <div class="col nav-link grew-link">
              {{user.get_username}}
            </div>
            <div class="col">
              <a class="nav-link grew-link" href="{% url 'logout' %}">Logout</a>
            </div>
          </div>
        </li>
        {% else %}
        <li class="nav-item"><a class="nav-link grew-link" href="{% url 'login'%}">Login</a></li>
        {% endif %}
      </ul>
      </ul>
    </div>
  </div>
</nav>

{% block page_content %}{% endblock %}