archive/grewtix/grewtix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('tickets.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

archive/grewtix/tickets/urls.py
from django.urls import path, re_path

from . import views

app_name = 'tickets'
urlpatterns = [
    path('', views.index, name='index'),
    path('owned_by_user_queue/', views.OwnedByUserView.as_view(), name='owned_by_user_queue'),
    path('created_by_user_queue/', views.CreatedByUserView.as_view(), name='created_by_user_queue'),
    path('unassigned_queue/', views.UnassignedView.as_view(), name='unassigned_queue'),
    path('recently_created_queue/', views.RecentlyCreatedView.as_view(), name='recently_created_queue'),
    path('all_ticket_queue/', views.AllTicketsView.as_view(), name='all_ticket_queue'),

    path('create/', views.TicketCreate.as_view(), name='create'),
    # re_path(r'^edit/[a-zA-Z]+[-][0-9]+', views.ticketedit, name='edit'),
    path('edit/<int:pk>', views.TicketUpdate.as_view(), name='edit'),
    path('<pk>/delete/', views.TicketDelete.as_view(), name='delete'),
    path('assign/<int:ticket_id>', views.TicketAssign, name="assign"),
    path('reports/', views.reports, name="reports")
    #path('comment/<int:comment>', views.CommentOnTicket, name="comment"),
]

grewtix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tickets/', include("tickets.urls")),
]

tickets/urls.py
from django.urls import path
from . import views

app_name = 'tickets'
urlpatterns = [
    path("", views.ticket_index, name="ticket_index"),
    path('create/', views.TicketCreate.as_view(), name='ticket_create'),
    path('detail/<int:pk>', views.TicketDetail.as_view(), name='ticket_detail'),
    path('edit/<int:pk>', views.TicketUpdate.as_view(), name='ticket_edit'),
    path('delete/<int:pk>', views.TicketDelete.as_view(), name='ticket_delete'),

    path('owner/', views.OwnedByUserView.as_view(), name='ticket_owner_queue'),
    path('created_by/', views.CreatedByUserView.as_view(), name='ticket_created_queue'),
    path('unassigned/', views.UnassignedView.as_view(), name='ticket_unassigned_queue'),
    path('recent/', views.RecentlyCreatedView.as_view(), name='ticket_recent_queue'),
    path('all/', views.AllTicketsView.as_view(), name='ticket_all_queue'),

    path('reports/', views.reports, name="ticket_reports"),
]

ttsystem/ttsystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('tickets.urls')),
    path('admin/', admin.site.urls),
]

archive/grewtix/tickets/models.py
from django.db import models
from django.utils import timezone, dateformat
from django.contrib.auth.models import User


# Create your models here.

class TimeStampMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class TicketType(TimeStampMixin): #1 to many
    ticketType = models.CharField(max_length=5)
    
    def __str__(self):
        return self.ticketType

class Project(TimeStampMixin): #1 to many
    project = models.CharField(max_length=50)

    def __str__(self):
        return self.project

class Priority(TimeStampMixin): #1 to many
    priority = models.CharField(max_length=10)

    def __str__(self):
        return self.priority

class Status(TimeStampMixin): #1 to many
    status = models.CharField(max_length=20)

    def __str__(self):
        return self.status

class Ticket(TimeStampMixin):

    PRIORITY_CHOICES = ( 
        ('Low','Low'),
        ('Medium','Medium'),
        ('High','High'),
        ('Critical','Critical'),
    )

    STATUS_CHOICES = ( 
        ('Backlog','Backlog'),
        ('Waiting On Submitter','Waiting On Submitter'),
        ('In Progress','In Progress'),
        ('Waiting On Support','Waiting On Support'),
    )

    ticketType = models.ForeignKey(TicketType, on_delete=models.CASCADE)
    subject = models.CharField(max_length=75)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    description = models.TextField(max_length=1000, default='')
    priority = models.CharField(max_length=10,choices=PRIORITY_CHOICES, blank=True) #Priority, on_delete=models.CASCADE, blank=True) #needs to be removed and replaced with list
    status = models.CharField(max_length=40,choices=STATUS_CHOICES, blank=True)
    creator = models.ForeignKey(User, related_name='creator', on_delete=models.CASCADE)
    owner = models.ForeignKey(User, related_name='owner', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.ticketType.ticketType + '-' + str(self.id)

    def how_many_days_old(self):
        # date_object = dateformat.format(timezone.now(), 'd' - dateformat.format(self.created_at,'d')
        delta = timezone.now() - self.created_at
        return delta.days

    def get_comments(self):
        queryset = Comment.objects.filter(ticketID=self.id)
        if queryset:
            return queryset
        else:
            return None

class Attachment(TimeStampMixin): #1 to many
    ticketID = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    filepath = models.CharField(max_length=150)

class Comment(TimeStampMixin): #1 to many
    ticketID = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    comment = models.CharField(max_length=500)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return 'Comment {} by {}'.format(self.comment, self.creator)

    def how_many_days_old(self):
        # date_object = dateformat.format(timezone.now(), 'd' - dateformat.format(self.created_at,'d')
        delta = timezone.now() - self.created_at
        return delta.days

tickets/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class TimeStampMixin(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class TicketType(TimeStampMixin):  # 1 to many
    ticketType = models.CharField(max_length=5)

    def __str__(self):
        return self.ticketType


class Project(TimeStampMixin):  # 1 to many
    project = models.CharField(max_length=20)

    def __str__(self):
        return self.project


class Ticket(TimeStampMixin):

    PRIORITY_CHOICES = (
        ('Low', 'Low'),
        ('Medium', 'Medium'),
        ('High', 'High'),
        ('Critical', 'Critical'),
    )

    STATUS_CHOICES = (
        ('Backlog', 'Backlog'),
        ('Waiting On Submitter', 'Waiting On Submitter'),
        ('In Progress', 'In Progress'),
        ('Waiting On Support', 'Waiting On Support'),
    )

    ticketType = models.ForeignKey(TicketType, on_delete=models.CASCADE)
    subject = models.CharField(max_length=75)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    description = models.TextField(max_length=1000, default='')
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES, blank=True)
    status = models.CharField(max_length=40, choices=STATUS_CHOICES, blank=True)
    creator = models.ForeignKey(User, related_name='creator', on_delete=models.CASCADE)
    owner = models.ForeignKey(User, related_name='owner', on_delete=models.CASCADE, blank=True, null=True)

    def how_many_days_old(self):
        delta = timezone.now() - self.created_at
        return delta.days

    def shortened_subject_str(self):
        return self.subject[0:20]

    def get_absolute_url(self):
        return reverse('tickets:ticket_detail', args=[str(self.id)])

    def __str__(self):
        return self.ticketType.ticketType + '-' + str(self.id)

archive/grewtix/tickets/forms.py
from django import forms
from .models import Ticket, Comment

class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        
        widgets = {
        #     'subject' : forms.TextInput(attrs={"class": "form-control-plaintext bg-light"})
            'description': forms.Textarea(),
            'creator': forms.HiddenInput(),
        }

        fields = [
            'ticketType',
            'subject',
            'project',
            'description',
            'priority',
            'status',
            'creator',
            'owner',
        ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment

        widgets = {
            'comment': forms.Textarea(),
            'creator': forms.HiddenInput(),
        }

        fields = ['comment', 'creator']

tickets/forms.py
from django import forms
from .models import Ticket


class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket

        widgets = {
            'description': forms.Textarea(),
            'creator': forms.HiddenInput(),
        }

        fields = [
            'ticketType',
            'subject',
            'project',
            'description',
            'priority',
            'status',
            'creator',
            'owner',
        ]

        # help_texts = {
        #     'subject': 'Group to which this message belongs to',
        # }

        # error_messages={
        #     'required': 'Please enter your name'
        # }

archive/grewtix/tickets/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic 
from django.urls import reverse
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.base import ContextMixin, TemplateResponseMixin
from django.http import HttpResponse, HttpResponseRedirect
from os import path

from .forms import TicketForm, CommentForm
from .models import Ticket, Comment

def TicketAssign(request, ticket_id):
    ticket = Ticket.objects.get(id=ticket_id)
    ticket.owner = User.objects.get(id=request.user.id)
    ticket.save()
    return HttpResponseRedirect(reverse('tickets:edit', kwargs={'pk': ticket.id}))

def CommentOnTicket(request, comment):
    pass

def index(request):
    return render(request, 'tickets/index.html')

# def ticketedit(request):
#     split_path = path.split(request.path)
#     ticket_split_by_dash = split_path[1].split('-')
#     ticket_id = ticket_split_by_dash[1]
#     if Ticket.objects.filter(pk=int(ticket_id)).exists():
#         ticket_object = Ticket.objects.get(pk=int(ticket_id))
#         if split_path[1].lower() == str(ticket_object).lower():
#             return HttpResponseRedirect(reverse('tickets:edit', kwargs={'pk': ticket_id}))
#     else:
#         return HttpResponse("Could not find the ticket you are looking for.") 

def reports(request):
    return render(request, 'tickets/ticket_reports.html')


##############################
# Returns different query sets for the ticket class
class TicketListView(generic.ListView):
    template_name = 'tickets/ticket_display_queryset.html'
    context_object_name = 'ticket_list'

class RecentlyCreatedView(TicketListView):
    def get_queryset(self):
        """Return the last five published Tickets."""
        return Ticket.objects.order_by('-created_at')[:4]

class OwnedByUserView(TicketListView):
    def get_queryset(self):
        return Ticket.objects.filter(owner=self.request.user.id).order_by('-created_at')

class CreatedByUserView(TicketListView):
    def get_queryset(self):
        return Ticket.objects.filter(creator=self.request.user.id).order_by('-created_at')

class UnassignedView(TicketListView):
    def get_queryset(self):
        return Ticket.objects.filter(owner=None).order_by('-created_at')

class AllTicketsView(TicketListView):
    def get_queryset(self):
        return Ticket.objects.all().order_by('-created_at')
##############################

##############################
# Handles all the CRUD operations for ticket
class TicketFormView():
    model = Ticket
    form_class = TicketForm

    def get_success_url(self):
        return reverse('tickets:index')

class TicketCreate(TicketFormView, CreateView):
    template_name = 'tickets/ticket_create_form.html'
    form_class = TicketForm

class TicketUpdate(TicketFormView, UpdateView):
    template_name = 'tickets/ticket_update_form.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # context['ticket_form'] = TicketForm
        context['comment_form'] = CommentForm
        print("********************************************************************************")
        return context

class TicketDelete(TicketFormView, DeleteView):
    pass

# class MultiFormViews(TemplateResponseMixin, BaseMul)

##############################

tickets/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from tickets.models import Ticket
from tickets.forms import TicketForm

# Create your views here.


@login_required
def ticket_index(request):
    return render(request, 'ticket_index.html')


@login_required
def reports(request):
    return render(request, 'ticket_reports.html')


class TicketListView(LoginRequiredMixin, generic.ListView):
    template_name = "ticket_display_queryset.html"
    context_object_name = 'ticket_list'
    paginate_by = 10
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'


class RecentlyCreatedView(TicketListView):
    def get_queryset(self):
        """Return the last five published Tickets."""
        return Ticket.objects.order_by('-created_at')[:4]


class OwnedByUserView(TicketListView):
    def get_queryset(self):
        return Ticket.objects.filter(owner=self.request.user.id).order_by('-created_at')


class CreatedByUserView(TicketListView):
    def get_queryset(self):
        return Ticket.objects.filter(creator=self.request.user.id).order_by('-created_at')


class UnassignedView(TicketListView):
    def get_queryset(self):
        return Ticket.objects.filter(owner=None).order_by('-created_at')


class AllTicketsView(TicketListView):
    def get_queryset(self):
        return Ticket.objects.all().order_by('-created_at')


class TicketFormView(LoginRequiredMixin):
    model = Ticket
    form_class = TicketForm
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'

    def get_success_url(self):
        return reverse('tickets:ticket_index')


class TicketCreate(TicketFormView, CreateView):
    template_name = 'ticket_create.html'


class TicketDetail(TicketFormView, DetailView):
    template_name = 'ticket_detail.html'


class TicketUpdate(TicketFormView, UpdateView):
    template_name = 'ticket_update.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # context['ticket_form'] = TicketForm
        return context


class TicketDelete(TicketFormView, DeleteView):
    template_name = 'ticket_confirm_delete.html'

archive/grewtix/tickets/templates/tickets/comment_form_template.html
{% load widget_tweaks %}


<div class="form-group row">
    <div class="col">
        {% render_field comment_form.comment class="form-control rounded-0" rows=3 %}
    </div>
    <div class="col-2">
        <input type='submit' value='Save' />
    </div>

</div>

{% render_field comment_form.creator value=user.id %}

archive/grewtix/tickets/templates/tickets/index.html
{% include 'tickets/design/header.html' %}


<div class="container">
    <br>
    <div class="list-group">
        <li class="list-group-item rectangle-link">
            <a href="{% url 'tickets:unassigned_queue' %}"><button type="button" class="btn btn-primary">Unassigned
                    Queue</button></a>
        </li>
        <li class="list-group-item rectangle-link">
            <a href="{% url 'tickets:owned_by_user_queue' %}"><button type="button" class="btn btn-primary">My
                    Queue</button></a>
        </li>
        <li class="list-group-item rectangle-link">
            <a href="{% url 'tickets:created_by_user_queue' %}"><button type="button" class="btn btn-primary">Created By
                    Me Queue</button></a>
        </li>
        <li class="list-group-item rectangle-link">
            <a href="{% url 'tickets:recently_created_queue' %}"><button type="button" class="btn btn-primary">Recently
                    Created Queue</button></a>
        </li>
        <li class="list-group-item rectangle-link">
            <a href="{% url 'tickets:all_ticket_queue' %}"><button type="button" class="btn btn-primary">All Tickets
                    Queue</button></a>
        </li>
    </div>
    <br>
</div>

{% include 'tickets/design/footer.html' %}

archive/grewtix/tickets/templates/tickets/ticket_create_form.html
{% include 'tickets/design/header.html' %}

<div class="container">
   
    <form method='POST'> {% csrf_token %}

        {% include 'tickets/ticket_form_template.html' %} 

    </form>
</div>

archive/grewtix/tickets/templates/tickets/ticket_display_queryset.html
{% include 'tickets/design/header.html' %}

<div class="container">
    <br>

    <div class="input-group w-100">
        <div class="form-outline w-75">
            <input type="search" id="search-form" class="form-control" />
        </div>
        <button type="button" class="btn">
            <i class="fas fa-search"></i>
        </button>
    </div>

    <br>
    
    {% if ticket_list %} 
        <ul class="list-group">
            {% for ticket in ticket_list %}
                <li class="list-group-item">
                    <a href="{%url 'tickets:assign' ticket.id %}">
                        <i style="padding-right: 10px;" class="fas fa-user-check"></i>
                    </a>
                    <a href="{%url 'tickets:delete' ticket.id %}">
                        <i style="padding-right: 10px;" class="fas fa-trash"></i>
                    </a>

                    <a href="{% url 'tickets:edit' ticket.id %}">{{ ticket }} : {{ticket.subject}}</a>
                    <p>Created by {{ ticket.creator }} 
        
                        {% if ticket.how_many_days_old > 0 %}
                            {{ticket.how_many_days_old }}
                            {% if ticket.how_many_days_old > 1 %}
                                days ago.
                            {% else %}
                                day ago.
                            {% endif %}
                        {% else %}
                            today.
                        {% endif %}
                    Assigned to {{ticket.owner}}</p>
                </li>                
            {% endfor %}
        </ul>
    {% else %}
        <p>No tickets are available</p>
    {% endif %}

</div>

archive/grewtix/tickets/templates/tickets/ticket_form_template.html
 {% load widget_tweaks %}


<div class="row">
	<!-- Blog Entries Column -->
	<div class="col-md-8">

		<h3 class="my-4">Create Ticket
          <small>{% render_field forms.ticket_form.ticketType class="form-control-dropdown" %}</small>
        </h3>
		<div class="form-group row">
			<label class="col-sm-2 col-form-label">Subject</label>
			<div class="col-sm-10"> {% render_field form.subject class="form-control-text" %} </div>
		</div>
		<div class="form-group row">
			<label for="" class="col-sm-2 col-form-label">Project</label>
			<div class="col-sm-10"> {% render_field form.project class="form-control-dropdown" %} </div>
		</div>
		<div class="form-group row">
			<label class="col-sm-2 col-form-label">Description</label>
			<div class="col-sm-10"> {% render_field form.description class="form-control-textarea" %} </div>
		</div>
		<div class="form-group row">
			<label class="col-sm-2 col-form-label">Priority</label>
			<div class="col-sm-10"> {% render_field form.priority class="form-control-dropdown" %} </div>
		</div>
		<div class="form-group row">
			<label class="col-sm-2 col-form-label">Status</label>
			<div class="col-sm-10"> {% render_field form.status class="form-control-dropdown" %} </div>

		</div>
		{% render_field form.creator value=user.id %}

		<input type='submit' value='Save' />
  </div>

	<!-- Sidebar Widgets Column -->
	<div class="col-md-4">

		<div class="card my-4">
			<div class="card-body">
				<div class="form-group row">
					<label class="col col-form-label">Assignee</label>
					<div class="col"> {% render_field form.owner class="form-control-dropdown bg-light" %} </div>
				</div>
			</div>
		</div>
		
		<div class="card my-4">
			<h5 class="card-header">Side Widget</h5>
			<div class="card-body">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut...</div>
		</div>

	</div>
</div>

archive/grewtix/tickets/templates/tickets/ticket_reports.html
{% include 'tickets/design/header.html' %}

<div class="container">
    This is the reports page..

    <div class="row">
        <div class="col-md-3">
            <div class="card-body">
                <h5 class="card-title">Total Tickets</h5>
                <p class="card-text">This is where the # goes.</p>
            </div>
        </div>
    </div>
</div>

archive/grewtix/tickets/templates/tickets/ticket_update_form.html
{% include 'tickets/design/header.html' %} 
<div class="container">
    <form method="post">{% csrf_token %}
    
        {% include 'tickets/ticket_form_template.html' %} 

    </form>


    <div class="container">

        <form method="post">{% csrf_token %}
    
            {% include 'tickets/comment_form_template.html' %} 
    
        </form>
    
        <ul class="list-group">
            {% for x in ticket.get_comments %}
            <li class="list-group-item">
                <p>{{ x }}</p> <a href="{% url 'tickets:index' %}"><i class="fas fa-edit"></i></a>
            </li>
            {% endfor %}
        </ul>
    </div>            

</div>